server:
  applicationConnectors:
  - type: http
    port: 8080

  adminConnectors:
  - type: http
    port: 8081

  requestLog:
    appenders: []

logging:
  level: INFO

  loggers:
    com.husqvarnagroup.dss.dl.connector: INFO
    org.glassfish.jersey: DEBUG

  appenders:
  - type: console
    threshold: ALL
    timeZone: UTC
    target: stdout
    logFormat: "%d{HH:mm:ss.SSS} %-5level [%thread][%logger{0}] %m%n"

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: etheder

  # the password
  password: Ethederpass

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/etheder

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

jobs:
  engineJob: 1min
  
#Caches
authCacheConfiguration: maximumSize=1000, expireAfterAccess=10m
